# Generated by Django 4.2.5 on 2023-10-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('hadm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admittime', models.DateTimeField()),
                ('dischtime', models.DateTimeField(null=True)),
                ('deathtime', models.DateTimeField(null=True)),
                ('admission_type', models.CharField(max_length=40)),
                ('admit_provider_id', models.CharField(max_length=10, null=True)),
                ('admission_location', models.CharField(max_length=60, null=True)),
                ('discharge_location', models.CharField(max_length=60, null=True)),
                ('insurance', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('marital_status', models.CharField(max_length=30, null=True)),
                ('race', models.CharField(max_length=80, null=True)),
                ('edregtime', models.DateTimeField(null=True)),
                ('edouttime', models.DateTimeField(null=True)),
                ('hospital_expire_flag', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edstay',
            fields=[
                ('stay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=60, null=True)),
                ('arrival_transport', models.CharField(max_length=50)),
                ('disposition', models.CharField(max_length=255, null=True)),
                ('hadm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=1)),
                ('anchor_age', models.IntegerField()),
                ('anchor_year', models.IntegerField()),
                ('anchor_year_group', models.CharField(max_length=255)),
                ('dod', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('heartrate', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('resprate', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('o2sat', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sbp', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('dbp', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pain', models.TextField(null=True)),
                ('acuity', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('chiefcomplaint', models.CharField(max_length=255, null=True)),
                ('stay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pyxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charttime', models.DateTimeField(null=True)),
                ('med_rn', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('gsn_rn', models.SmallIntegerField()),
                ('gsn', models.CharField(max_length=10, null=True)),
                ('stay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='edstay',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.IntegerField()),
                ('icd_code', models.CharField(max_length=10)),
                ('icd_version', models.IntegerField()),
                ('icd_title', models.TextField()),
                ('stay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
