# Generated by Django 4.2.5 on 2023-09-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='stay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay'),
        ),
        migrations.AlterField(
            model_name='pyxis',
            name='stay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='stay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edstay'),
        ),
    ]
